{% set version = "0.4.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-textshaping
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/textshaping_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/textshaping/textshaping_{{ version }}.tar.gz
  sha256: 238a5ef2d673948ff3f440dd88b5ae0e9ce5c6e44d22269091d604d7b8b5301e

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-cpp11                      # [build_platform != target_platform]
    - r-systemfonts                # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - freetype
    - harfbuzz
    - fribidi
    - glib     # [osx]
    - libglib  # [osx]
    - r-cpp11 >=0.2.1
    - r-systemfonts >=1.0.0
  run:
    - r-base
    - freetype
    - harfbuzz
    - fribidi
    - r-cpp11 >=0.2.1
    - r-systemfonts >=1.0.0

test:
  commands:
    - $R -e "library('textshaping')"           # [not win]
    - "\"%R%\" -e \"library('textshaping')\""  # [win]

about:
  home: https://github.com/r-lib/textshaping
  license: MIT
  summary: Provides access to the text shaping functionality in the 'HarfBuzz' library and the bidirectional algorithm in the 'Fribidi' library. 'textshaping' is a low-level utility package mainly for graphic devices that expands upon the font tool-set provided by the 'systemfonts' package.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
